//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taske_id { get; set; }
        public string task_title { get; set; }
        public string task_descrip { get; set; }
        public string task_status { get; set; }
        public Nullable<System.DateTime> task_duedate { get; set; }
        public string employee_name { get; set; }
    }
}
